// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plgrtfhylvzmlknelfhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsZ3J0Zmh5bHZ6bWxrbmVsZmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzI0MDEsImV4cCI6MjA3MjIwODQwMX0.-ZStG6pB-XAii1khUToMCODcUc98B71m1GN61WavBYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});